"""add_server_moniter

Revision ID: a4a0878b6525
Revises: eefcca423919
Create Date: 2017-11-15 12:00:53.517554

"""

# revision identifiers, used by Alembic.
revision = 'a4a0878b6525'
down_revision = 'eefcca423919'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_monitor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpu_info', sa.String(length=1000), nullable=True),
    sa.Column('disks_info', sa.String(length=1000), nullable=True),
    sa.Column('memory_info', sa.String(length=1000), nullable=True),
    sa.Column('network_info', sa.String(length=1000), nullable=True),
    sa.Column('sensors_info', sa.String(length=1000), nullable=True),
    sa.Column('moniter_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('server_monitor')
    # ### end Alembic commands ###
