"""add nexapi

Revision ID: cd89a8474017
Revises: 51f5ccfba190
Create Date: 2017-07-19 10:17:38.371924

"""

# revision identifiers, used by Alembic.
revision = 'cd89a8474017'
down_revision = '51f5ccfba190'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nex_api_case',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('desc', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=100), nullable=True),
    sa.Column('request_type', sa.String(length=100), nullable=True),
    sa.Column('request_data', sa.Text(), nullable=True),
    sa.Column('expectation', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nex_api_case')
    # ### end Alembic commands ###
