"""add nexapiconfig

Revision ID: eefcca423919
Revises: cd89a8474017
Create Date: 2017-07-27 14:57:41.376474

"""

# revision identifiers, used by Alembic.
revision = 'eefcca423919'
down_revision = 'cd89a8474017'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nex_api_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('desc', sa.String(length=100), nullable=True),
    sa.Column('config', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nex_api_config')
    # ### end Alembic commands ###
